spring:
  application:
    name: tasks-backend
  h2:
    console:
      enabled: true
      path: /h2-console # URL de acesso: localhost:8080/h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE # H2 em memória, nome 'testdb'
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  data:
    rest:
      base-path: /api
      defaultMediaType: application/json
logging:
  level:
    root: INFO